# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_convex.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyResult(object):
    def setupUi(self, MyResult):
        MyResult.setObjectName("MyResult")
        MyResult.resize(873, 753)
        font = QtGui.QFont()
        font.setPointSize(11)
        MyResult.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MyResult)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(190, 140, 581, 521))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 50, 93, 29))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 50, 93, 29))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 50, 93, 29))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 330, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MyResult.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MyResult)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 29))
        self.menubar.setObjectName("menubar")
        MyResult.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MyResult)
        self.statusbar.setObjectName("statusbar")
        MyResult.setStatusBar(self.statusbar)

        self.retranslateUi(MyResult)
        QtCore.QMetaObject.connectSlotsByName(MyResult)

    def retranslateUi(self, MyResult):
        _translate = QtCore.QCoreApplication.translate
        MyResult.setWindowTitle(_translate("MyResult", "MainWindow"))
        self.label.setText(_translate("MyResult", "测试的函数："))
        self.pushButton.setText(_translate("MyResult", "Test_1"))
        self.pushButton_2.setText(_translate("MyResult", "Test_2"))
        self.pushButton_3.setText(_translate("MyResult", "Test_3"))
        self.label_2.setText(_translate("MyResult", "最终的迭代收敛图："))
